drop table if exists tbl_shift_data CASCADE;
drop table if exists tbl_user CASCADE;
create table tbl_shift_data (index bigint generated by default as identity, created_on timestamp, shift_status integer, user_id varchar(255), primary key (index));
create table tbl_user (user_id varchar(255) not null, created_on timestamp, shift_status integer, updated_on timestamp, primary key (user_id));